using System;
using UnityEngine;

namespace _MyFiles.Scripts.Managers
{
    public class GameInputManager : MonoBehaviour
    {
        //The C# class Generated by the Input System
        public DKinputSystem_Actions InputActions;
        
        [SerializeField] private bool wasLockedInBeforeUI = false;

        private void Awake()
        {
            InputActions = new DKinputSystem_Actions();

            InputActions.PlayerLockedIn.Exit_Cabinet.performed += ctx => EnableFreeRoam();
        }

        private void OnEnable()
        {
            //Start the game in free roam mode
            //EnableFreeRoam();
            EnableCabinetPlay();
        }

        private void OnDisable()
        {
            //Always disable inputs when the object is destroyed
            InputActions.Disable();
        }

        public void EnableFreeRoam()
        {
            InputActions.UI.Disable();
            InputActions.PlayerLockedIn.Disable();
            
            InputActions.PlayerFreeRoaming.Enable();
            Debug.Log("Switched to Free Roam: Player is can walk around.");
        }

        public void EnableCabinetPlay()
        {
            InputActions.PlayerFreeRoaming.Disable();
            InputActions.UI.Disable();
            
            InputActions.PlayerLockedIn.Enable();
            Debug.Log("Switched to Cabinet: Player is locked in. DK controls active.");
        }

        public void ToggleUI(bool bisUIEnabled)
        {
            if (bisUIEnabled)
            {
                // 1. Remember the state BEFORE we turn gameplay off
                wasLockedInBeforeUI = InputActions.PlayerLockedIn.enabled;

                // 2. Turn ON the UI, turn OFF gameplay
                InputActions.PlayerFreeRoaming.Disable();
                InputActions.PlayerLockedIn.Disable();

                InputActions.UI.Enable();
                Debug.Log("Switched to UI: Menus Active");
            }
            else
            {
                // Turn OFF the UI
                InputActions.UI.Disable();

                // 3. Return to the saved state
                if (wasLockedInBeforeUI)
                {
                    InputActions.PlayerLockedIn.Enable();
                    Debug.Log("Switched back to Cabinet from UI");
                }
                else
                {
                    InputActions.PlayerFreeRoaming.Enable();
                    Debug.Log("Switched back to Free Roam from UI");
                }
            }
        }
    }
}
